### ISSUE TITLE
Couldn't interact with pdf

### ISSUE THREAD

**Issue by The-CodeINN** [anand-mukul/PDFNinja#2]
I uploaded a pdf with only one page, yet I can't interact with the bot
![screenshot-pdfninja vercel app-2023 10 21-10_32_31](https://github.com/anand-mukul/PDFNinja/assets/67247138/acb1f212-74e0-46db-8435-faf2cf7d91c6)

**Comment by anand-mukul** [comment]
You can use it on localhost as it's intergrated with third party that's not free.
Because, I removed .env
