### ISSUE TITLE
Error: 752-b6241ee8dae97ba2.js:17   POST https://pdfninja-new.vercel.app/api/trpc/getFile?batch=1 404 (Not Found)

### ISSUE THREAD

**Issue by Omsoni06** [anand-mukul/PDFNinja#4]

**Comment by anand-mukul** [comment]
### Issue Resolution

1. **Node.JS Troubleshooting:** Check this pinecone support docs [here](https://support.pinecone.io/hc/en-us/articles/9570011184797-Node-JS-Troubleshooting).

2. **Vercel Timeout:** Tasks timeout after 10 seconds on Vercel; consider upgrading to a paid plan.

### Suggestion

Run the application locally with all required environment variables.

Let me know if you need further assistance.
